### ISSUE TITLE
Getting Error with Glyphs 3.2

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/Shadow#3]
in 3180:
```py
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 622, in process_
  File "plugin.py", line 248, in filter
    shadowLayer.applyTransform( offsetMatrix )
  File "GlyphsApp/GlyphsApp/__init__.py", line 8805, in __GSLayer_applyTransform__
ValueError: NSInvalidArgumentException - -[OC_BuiltinPythonArray transformPoint:]: unrecognized selector sent to instance 0x600000029df0
```

in 3179:
```py
Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 622, in process_
  File "plugin.py", line 248, in filter
    shadowLayer.applyTransform( offsetMatrix )
  File "GlyphsApp/GlyphsApp/__init__.py", line 8800, in __GSLayer_applyTransform__
NameError: name 'NSAffineTransformStruct' is not defined
```

in 3151 it works perfectly

Glyphs Python 3.9.1

@schriftgestalt

**Comment by schriftgestalt** [comment]
I fixed that just after uploading 3180.
